[package]
name = "chart1"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono = { version="0.4.39", features = ["serde"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "=1.0.133"
[target.'cfg(windows)'.dependencies]
plotly = "0.11.0"

[[bin]]
path = "./chart1.rs"
name = "chart1"


