[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# default-run = "edge"

[workspace]
members = [
    "cmd/edge", "cmd/itr", "cmd/bm", "cmd/ub", "cmd/setbuff", "cmd/chart1",
    "cmd/train", "cmd/detect3",
    "crates/can_data", "crates/can_utils", "crates/utils",
    "crates/medius_data", "crates/medius_model","crates/medius_meta", "crates/medius_parser",
]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.95", features = ["backtrace"] }
#candle-core = { version = "0.8.1", features = ["cuda"] }
candle-core = "0.8.2"
candle-nn = "0.8.2"
clap = { version = "4.5.26", features = ["derive"] }
#cudarc = { version = "0.12.2", features = ["std", "cublas", "cublaslt", "curand", "driver", "nvrtc", "f16", "cuda-version-from-build-system", "dynamic-linking"], default-features=false }
rand = "0.8.5"
chrono = { version="0.4.39", features = ["serde"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.135"
serde_yaml = "0.9"
safetensors = "0.5.2"



