[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
default-run = "edge"

[workspace]
members = [  "cmd/edge", 
	"crates/can_data", "crates/can_utils", 
]
resolver = "2"

[workspace.dependencies]
candle-core = "0.6.0"
candle-nn = "0.6.0"

# https://stackoverflow.com/questions/57017066/how-do-i-set-environment-variables-with-cargo
# [env]
# CUDA_TOOLKIT_ROOT_DIR = { value= "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8", force = true }
# CUDA_PATH = { value= "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8", force = true }
# FOO = "bar"
# PATH_TO_SOME_TOOL = { value = "bin/tool", relative = true }
# USERNAME = { value = "test_user", force = true }

