[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
default-run = "edge"

[workspace]
members = [
	"cmd/edge",
	"crates/can_data", "crates/can_utils", 
]
resolver = "2"

[workspace.dependencies]
candle-core = "0.6.0"
candle-nn = "0.6.0"

[target.'cfg(any(target_arch = "arm", target_arch = "aarch64"))']
rustflags = ["-C", "target-feature=+fp16"]