[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# default-run = "edge"

[workspace]
members = [
    "cmd/edge", "cmd/itr", "cmd/bm", "cmd/ub", "cmd/setbuff", "cmd/chart1", "cmd/train", "cmd/detect3",
    "crates/can_data", "crates/can_utils", "crates/medius_data", "crates/medius_model",
]
resolver = "2"

[workspace.dependencies]
accelerate-src = { version = "0.3.2" }
anyhow = { version = "1", features = ["backtrace"] }
candle-core = "0.8.0"
candle-nn = "0.8.0"
candle-datasets = "0.8.0"
intel-mkl-src = { version = "0.8.1", features = ["mkl-static-lp64-iomp"] }
clap = { version = "4.2.4", features = ["derive"] }
rand = "0.8.5"


