[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# default-run = "edge"

[workspace]
members = [
	"cmd/edge", "cmd/itr", "cmd/bm", "cmd/ub",
	"crates/can_data", "crates/can_utils", 
]
resolver = "2"

[workspace.dependencies]
candle-core = "0.7.1"
candle-nn = "0.7.1"

