[package]
name = "ub"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
crossbeam-channel = "0.5.13"
ctrlc = "3.4.5"

[[bin]]
path = "./ub.rs"
name = "ub"


