[package]
name = "medius_parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
candle-core = { workspace = true }
rand = { workspace = true }
# microfft = "0.6.0"
pacmog = "0.5.0"
rustfft = "6.2.0"
# may not be used on the stable release channel
# phastft = "0.2.1"

[lib]
path = "./medius_parser.rs"
