[package]
name = "dur"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
clipboard.workspace = true
[[bin]]
path = "./dur.rs"
name = "dur"


