[package]
name = "itr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
candle-core = { workspace = true }
candle-nn = { workspace = true }

[features]
default = ["cuda"]
cuda = []

[[bin]]
path = "./itr.rs"
name = "itr"


