[package]
name = "bm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
indicatif.workspace = true
sysinfo.workspace = true
[[bin]]
path = "./bm.rs"
name = "bm"


