[package]
name = "medius_server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
actix-web = "4.9.0"
actix-multipart = "0.7.2"
futures-util = "0.3.31"
crc32fast = "1.4.2"
medius_model = { path = "../../crates/medius_model" }