[package]
name = "medius_data"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
candle-core = { workspace = true }
rand = { workspace = true }
utils = { path = "../../crates/utils" }
csv = "1.3.1"

[lib]
path = "./medius_data.rs"